version: "2"

linters:
  default: all
  enable:
    - gomodguard_v2
    - errcheck
  disable:
    - gomodguard
    - containedctx
    - depguard
    - dupl
    - err113
    - funlen
    - gocyclo
    - inamedparam
    - ireturn
    - maintidx
    - mnd
    - nestif
    - noinlineerr
    - tagliatelle
    - wsl
    - wsl_v5
  exclusions:
    paths:
      - testdata/
    rules:
      - path: _test\.go
        linters:
          - cyclop
          - gocognit
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    
formatters:
  enable:
    - gofumpt
